providers:
  docker:
    defaultRule: "Host(`{{trimPrefix '/' .Name}}.docker.localhost`)"
    exposedByDefault: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

certificatesResolvers:
  myresolver:
    acme:
      dnschallenge:
        provider: ovh
      email: jeremy.tomasi.pro@gmail.com
      storage: /letsencrypt/acme.json

api:
  insecure: true